
[ballerina.observe]
metricsEnabled=true
metricsReporter="prometheus"
tracingEnabled=true
tracingProvider="jaeger"

[ballerinax.prometheus]
host="0.0.0.0"
port=9797

[ballerinax.jaeger]
agentHostname="localhost"
agentPort=6831
samplerType="const"
samplerParam=1.0

[ballerinax.choreo]
reporterHostname="periscope.choreo.dev"
reporterPort=443
reporterUseSSL=true
