[[dependency]]
org = "ballerinax"
name = "choreo"
version = "0.3.0"

[[dependency]]
org = "ballerinax"
name = "jaeger"
version = "0.2.3"

[[dependency]]
org = "ballerinax"
name = "prometheus"
version = "0.1.8"


