name: Build Branch

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  ballerina_pack_build_with_build_cache:
    name: Build Ballerina Pack with Cache
    strategy:
      matrix:
        os: ["ubuntu-20.04"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Pack
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make ballerina-pack.build.with-cache
      - name: Upload Pack
        uses: actions/upload-artifact@v2
        with:
          name: Ballerina Pack (${{ matrix.os }})
          if-no-files-found: error
          path: packs/ballerina-*.zip
  ballerina_pack_build:
    name: Build Ballerina Pack
    strategy:
      matrix:
        os: ["ubuntu-20.04"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Cloning repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build Pack
      env:
        packageUser: ${{ github.actor }}
        packagePAT: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make ballerina-pack.build
  test_pack_build_in_place_update:
    name: Test Ballerina Pack in-place Update
    needs: ballerina_pack_build_with_build_cache
    strategy:
      matrix:
        os: ["ubuntu-20.04"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Pack
        uses: actions/download-artifact@v2
        with:
          name: Ballerina Pack (${{ matrix.os }})
          path: packs
      - name: Unzip Pack
        run: bash scripts/ballerina-pack/unzipPack.sh
      - name: In-place Update
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make ballerina-pack.build.in-place-update
  test_projects:
    name: Test Build Projects
    needs: ballerina_pack_build_with_build_cache
    strategy:
      matrix:
        os: ["ubuntu-20.04"]
        project: ["hello_world_service", "simple_passthrough", "chained_ballerina_service"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Pack
        uses: actions/download-artifact@v2
        with:
          name: Ballerina Pack (${{ matrix.os }})
          path: packs
      - name: Unzip Pack
        run: bash scripts/ballerina-pack/unzipPack.sh
      - name: Test Project
        env:
          TEST_PROJECT_NAME: ${{ matrix.project }}
        run: |
          make ballerina-project.${TEST_PROJECT_NAME}.build
