name: Build Branch

on:
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  ballerina_pack_build_with_build_cache:
    name: Build Ballerina Pack with Cache
    runs-on: ubuntu-20.04
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Pack
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make ballerina-pack.build.with-cache
  ballerina_pack_build:
    name: Build Ballerina Pack
    runs-on: ubuntu-20.04
    steps:
    - name: Cloning repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build Pack
      env:
        packageUser: ${{ github.actor }}
        packagePAT: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make ballerina-pack.build
    - name: Upload Pack
      uses: actions/upload-artifact@v2
      with:
        name: Ballerina Pack
        if-no-files-found: error
        path: packs/ballerina-*
  ballerina_pack_build_in_place_update:
    name: Build Ballerina Pack in-place Update
    needs: ballerina_pack_build
    runs-on: ubuntu-20.04
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Pack
        uses: actions/download-artifact@v2
        with:
          name: Ballerina Pack
          path: packs
      - name: In-place Update
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make ballerina-pack.build.in-place-update
