on:
  push:
    branches:
    - "master"
  schedule:
  - cron: "0 0 * * *"
jobs:
  docker_build:
    name: "Build Docker Images"
    runs-on: "ubuntu-20.04"
    steps:
    - name: "Cloning repository"
      uses: "actions/checkout@v2"
      with:
        submodules: "recursive"
    - name: "Caching Maven Dependencies"
      uses: "actions/cache@v1"
      with:
        path: "~/.m2/repository"
        key: "${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}"
    - name: "Build Artifacts"
      run: |
        pushd docker/artifacts
        bash build.sh
        popd
    - name: "Build and Push Netty Backend Image"
      uses: docker/build-push-action@v1
      with:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
        path: "./docker"
        dockerfile: "./docker/netty-backend/Dockerfile"
        repository: "nadunrds/ballerina-dev-kit-netty-backend"
        tags: "latest"
        tag_with_sha: true
        always_pull: true
        add_git_labels: true
        push: true
